name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install coverage flake8

      # 4. Проверка кода линтером
      - name: Run linter (flake8)
        run: flake8 .

      # 5. Запуск тестов с coverage
      - name: Run tests with coverage
        run: |
          python3 -m coverage run -m unittest discover .
          python3 -m coverage report
          python3 -m coverage html  # генерируем HTML отчёт

      # 6. Загрузка HTML-отчёта как артефакта
      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-${{ matrix.os }}  # отдельный артефакт для каждой ОС
          path: htmlcov
